// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApsZsQYTGTI2-seRUcq4OgvI3iMJ6VwbI',
    appId: '1:689680719346:web:b811889f43234a5c58df6b',
    messagingSenderId: '689680719346',
    projectId: 'deliveryapp-77614',
    authDomain: 'deliveryapp-77614.firebaseapp.com',
    storageBucket: 'deliveryapp-77614.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqjzAJ8O4wX3fOCDpZFQp3UbX_X5LeAEI',
    appId: '1:689680719346:android:7eb960e4f9bf977258df6b',
    messagingSenderId: '689680719346',
    projectId: 'deliveryapp-77614',
    storageBucket: 'deliveryapp-77614.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQH-MOIUzn-lD-01Wo_RRvFBvUTBGm5Ao',
    appId: '1:689680719346:ios:58f431e15da6c29158df6b',
    messagingSenderId: '689680719346',
    projectId: 'deliveryapp-77614',
    storageBucket: 'deliveryapp-77614.appspot.com',
    iosBundleId: 'com.servicebookingapp.serviceBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQH-MOIUzn-lD-01Wo_RRvFBvUTBGm5Ao',
    appId: '1:689680719346:ios:58f431e15da6c29158df6b',
    messagingSenderId: '689680719346',
    projectId: 'deliveryapp-77614',
    storageBucket: 'deliveryapp-77614.appspot.com',
    iosBundleId: 'com.servicebookingapp.serviceBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApsZsQYTGTI2-seRUcq4OgvI3iMJ6VwbI',
    appId: '1:689680719346:web:eff111d3faaa055b58df6b',
    messagingSenderId: '689680719346',
    projectId: 'deliveryapp-77614',
    authDomain: 'deliveryapp-77614.firebaseapp.com',
    storageBucket: 'deliveryapp-77614.appspot.com',
  );

}